id: PABFCEAA5
initial_creation_type: ocr
source_metadata:
  volumes:
    d717c209bc484fc2bb8f876fcb7403d7:
      base_file: v005.txt
      image_group_id: I1PD95850
      title: གཏོར་མའི་ཆོ་ག།
      total_pages: 2069
      volume_number: 5
